negocios=[
    {
        "ruc":857496321,
        "nombre":"el pichilon",
        "categoria":["bodega"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"edwin"
    },
    {
        "ruc":481234987,
        "nombre":"pepe",
        "categoria":["abarrotes"],
        "horario_atencion":{
            "dia":"6am-12m",
            "tarde":"1pm-7pm"
        },
        "gerente":"nadine"
    },
    {
        "ruc":8574963,
        "nombre":"las chaqueteadas",
        "categoria":["farmacia","bodega","restaurant"],
        "horario_atencion":{
            "dia":"8am-12m",
            "tarde":"2pm-10pm"
        },
        "gerente":"china"
    },
    {
        "ruc":85749771,
        "nombre":"las sirenitas",
        "categoria":["restaurant"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"cristian"
    },
    {
        "ruc":16472121,
        "nombre":"chaqueteros",
        "categoria":["farmacia"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"cristian"
    },
    {
        "ruc":85321,
        "nombre":"papus",
        "categoria":["bodega"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"cristian"
    },
    {
        "ruc":857496321454646,
        "nombre":"el pichilon 2",
        "categoria":["bodega"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"nadine"
    },
    {
        "ruc":11123461,
        "nombre":"xd",
        "categoria":["restaurant"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"edwin"
    },
    {
        "ruc":857000478,
        "nombre":"jijijia",
        "categoria":["farmacia"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"nadine"
    },
    {
        "ruc":13516715,
        "nombre":"el pichilon 3",
        "categoria":["bodega"],
        "horario_atencion":{
            "dia":"7am-12m",
            "tarde":"2pm-8pm"
        },
        "gerente":"china"
    }
]